theme = "hugo-coder"
baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Christian Vahrenkamp"
Headtitle="Headtitle"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

  
[pagination]
pagerSize = 20



[markup.highlight]
style = "github-dark"

[markup]
  [markup.tableOfContents]
    startLevel = 2     # include <h2>
    endLevel   = 2     # include <h3>
    ordered    = true  # unordered list

[params]
author = "Christian Vahrenkamp"
info="Data Scientist"
description="Data Scientist specialized in NLP"
keywords="Large Language Model"
avatarURL ="Image1.png"
#gravatar="christian@t-online.de"
disableDefaultJsScripts = false
colorScheme = "auto"
hidecolorschemetoggle = false
#customCSS = ["css/heading-numbers.css"]


[params.utterances]
  repo = "https://github.com/cvhrnkmp/cvhrnkmp.github.io.git" # https://utteranc.es/#heading-repository
  issueTerm = "pathname" # https://utteranc.es/#heading-mapping
  label = "anonymous" # https://utteranc.es/#heading-issue-label
  theme = "preferred-color-scheme" # https://utteranc.es/#heading-theme

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
 
# Social
  [[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/cvhrnkmp/"
  [[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/christian-vahrenkamp/"
